
# Netlify configuration for deployment
[build]
  command = "npm install -g vite@6.2.1 && npm install vite@6.2.1 @vitejs/plugin-react-swc@latest -D && npm ci --legacy-peer-deps && npx vite build"
  publish = "dist"
  functions = "netlify/functions"
  
# Specify Node.js version
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_ENV = "production"
  VITE_VERSION = "6.2.1"
  # Enable verbose logging for npm
  NPM_FLAGS = "--verbose --legacy-peer-deps"
  CACHE_DEPS = "true"
  
# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# ... keep existing code (Cache for fonts and images headers)

# Performance optimization headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    
# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_VERSION = "6.2.1"
  # Enable verbose logging for npm
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Add specific settings for preview deployments
[context.deploy-preview]
  command = "npm install -g vite@6.2.1 && npm install vite@6.2.1 @vitejs/plugin-react-swc@latest -D && npm ci --legacy-peer-deps && npx vite build"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_VERSION = "6.2.1"
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Branch deploy settings
[context.branch-deploy]
  command = "npm install -g vite@6.2.1 && npm install vite@6.2.1 @vitejs/plugin-react-swc@latest -D && npm ci --legacy-peer-deps && npx vite build"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_VERSION = "6.2.1"
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Enable bundler
[dev]
  command = "npm run dev"
  framework = "#custom"
  targetPort = 8080

# Caching configuration for build optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Post-processing for better performance
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Use a more reliable cache plugin
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      "node_modules/.vite",
      ".netlify/functions",
      ".netlify/plugins",
      "dist"
    ]
