
# Netlify configuration for deployment
[build]
  command = "npm install vite@5.0.0 @vitejs/plugin-react-swc@latest --no-save && npm ci --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"
  
# Specify Node.js version
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = ">=9"  # Updated to accept npm 9 or higher
  VITE_APP_ENV = "production"
  VITE_VERSION = "5.0.0"  # Explicitly set Vite version
  # Disable unnecessary language installations
  SKIP_GO_INSTALL = "true"
  SKIP_PYTHON_INSTALL = "true"
  SKIP_RUBY_INSTALL = "true"
  SKIP_RUST_INSTALL = "true"
  
# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Cache for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Cache for fonts and images
[[headers]]
  for = "*.{woff,woff2,ttf,otf,png,jpg,jpeg,gif,webp,svg}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Performance optimization headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    
# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
  NPM_VERSION = ">=9"
  VITE_VERSION = "5.0.0"

# Add specific settings for preview deployments
[context.deploy-preview]
  command = "npm install vite@5.0.0 @vitejs/plugin-react-swc@latest --no-save && npm ci --legacy-peer-deps && npm run build"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
  NPM_VERSION = ">=9"
  VITE_VERSION = "5.0.0"

# Branch deploy settings
[context.branch-deploy]
  command = "npm install vite@5.0.0 @vitejs/plugin-react-swc@latest --no-save && npm ci --legacy-peer-deps && npm run build"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
  NPM_VERSION = ">=9"
  VITE_VERSION = "5.0.0"

# Dev settings
[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080
  framework = "#custom"
  publish = "dist"
  autoLaunch = false
  
# Post-processing settings
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Use Netlify's improved cache plugins
[[plugins]]
  package = "@netlify/plugin-nextjs-cache"
  
[[plugins]]
  package = "netlify-plugin-cache"  
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      "node_modules/.vite",
      ".netlify/functions-serve",
      ".netlify/cache/.vite",
      "dist"
    ]

# Configure feed fetching with error handling
[[plugins]]
  package = "netlify-plugin-fetch-feeds"
  [plugins.inputs]
    dataDir = "src/data/feeds"
    failBuildOnError = false
    feeds = [
      { name = "css-tricks", url = "https://www.xml-sitemaps.com/download/css-tricks.com-67fb017b/sitemap.xml?view=1", format = "xml" },
      { name = "netlify", url = "https://www.netlify.com/sitemap.xml", format = "xml" }
    ]
