
# Netlify configuration for deployment
[build]
  command = "npm run build"
  publish = "dist"
  
# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Cache for fonts
[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache for images (can be revalidated)
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Performance optimization headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    # Enable compression
    Content-Encoding = "br"
    # Preload key assets
    Link = "</assets/js/vendor-react-*.js>; rel=preload; as=script, </assets/js/vendor-ui-*.js>; rel=preload; as=script"
    
# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"

# Enable bundler
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true
[build.processing.html]
  pretty_urls = true
