
# Netlify configuration for deployment
[build]
  command = "npm install vite@5.0.0 --save-dev && npm ci --legacy-peer-deps && npx vite build"
  publish = "dist"
  functions = "netlify/functions"
  
# Specify Node.js version
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_ENV = "production"
  # Enable verbose logging for npm
  NPM_FLAGS = "--verbose --legacy-peer-deps"
  
# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Cache for fonts
[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache for images (can be revalidated)
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Performance optimization headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    
# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Enable verbose logging for npm
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Add specific settings for preview deployments
[context.deploy-preview]
  command = "npm install vite@5.0.0 --save-dev && npm ci --legacy-peer-deps && npx vite build"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Branch deploy settings
[context.branch-deploy]
  command = "npm install vite@5.0.0 --save-dev && npm ci --legacy-peer-deps && npx vite build"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Enable bundler
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true
[build.processing.html]
  pretty_urls = true
