
# Netlify configuration for deployment
[build]
  command = "npm install vite@6.2.1 @vitejs/plugin-react-swc@latest --no-save && npm ci --no-fund --prefer-offline --legacy-peer-deps && npx vite build --debug --mode production"
  publish = "dist"
  functions = "netlify/functions"
  
# Specify Node.js version
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_ENV = "production"
  VITE_VERSION = "6.2.1"
  NODE_ENV = "production"
  # Disable unnecessary language installations
  SKIP_GO_INSTALL = "true"
  SKIP_PYTHON_INSTALL = "true"
  SKIP_RUBY_INSTALL = "true"
  SKIP_RUST_INSTALL = "true"
  # Enable verbose logging for npm
  NPM_FLAGS = "--verbose --no-fund --prefer-offline --legacy-peer-deps"
  CACHE_DEPS = "true"
  
# ... keep existing code (handle SPA routing redirects)
  
# ... keep existing code (Cache for static assets headers)
    
# ... keep existing code (Cache for fonts and images headers)

# Performance optimization headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    
# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_VERSION = "6.2.1"
  SKIP_GO_INSTALL = "true"
  SKIP_PYTHON_INSTALL = "true"
  SKIP_RUBY_INSTALL = "true"
  SKIP_RUST_INSTALL = "true"
  # Enable verbose logging for npm
  NPM_FLAGS = "--verbose --no-fund --prefer-offline --legacy-peer-deps"

# Add specific settings for preview deployments
[context.deploy-preview]
  command = "npm install vite@6.2.1 @vitejs/plugin-react-swc@latest --no-save && npm ci --no-fund --prefer-offline --legacy-peer-deps && npx vite build --debug --mode production"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_VERSION = "6.2.1"
  SKIP_GO_INSTALL = "true"
  SKIP_PYTHON_INSTALL = "true"
  SKIP_RUBY_INSTALL = "true"
  SKIP_RUST_INSTALL = "true"
  NPM_FLAGS = "--verbose --no-fund --prefer-offline --legacy-peer-deps"

# Branch deploy settings
[context.branch-deploy]
  command = "npm install vite@6.2.1 @vitejs/plugin-react-swc@latest --no-save && npm ci --no-fund --prefer-offline --legacy-peer-deps && npx vite build --debug --mode production"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_VERSION = "6.2.1"
  SKIP_GO_INSTALL = "true"
  SKIP_PYTHON_INSTALL = "true"
  SKIP_RUBY_INSTALL = "true"
  SKIP_RUST_INSTALL = "true"
  NPM_FLAGS = "--verbose --no-fund --prefer-offline --legacy-peer-deps"

# ... keep existing code (dev settings, bundler and caching configuration)

# ... keep existing code (post-processing settings for performance)

# Use Netlify's built-in caching for Vite projects
[[plugins]]
  package = "@netlify/plugin-gatsby"
  [plugins.inputs]
    checkLatestVersion = false

[[plugins]]
  package = "netlify-plugin-cache"  
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      "node_modules/.vite",
      ".netlify/functions-serve",
      ".netlify/cache/.vite",
      "dist"
    ]
