
# Netlify configuration for deployment
[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
