
# Netlify configuration for deployment
[build]
  command = "npm i vite @vitejs/plugin-react-swc -D && node --experimental-modules netlify/functions/updatePackageJson.js && npm ci --legacy-peer-deps && npx vite build --config vite.config.ts"
  publish = "dist"
  functions = "netlify/functions"
  
# Specify Node.js version
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_ENV = "production"
  # Enable verbose logging for npm
  NPM_FLAGS = "--verbose --legacy-peer-deps"
  
# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# ... keep existing code (Cache for fonts and images headers)

# Performance optimization headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    
# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Enable verbose logging for npm
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Add specific settings for preview deployments
[context.deploy-preview]
  command = "npm i vite @vitejs/plugin-react-swc -D && node --experimental-modules netlify/functions/updatePackageJson.js && npm ci --legacy-peer-deps && npx vite build --config vite.config.ts"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Branch deploy settings
[context.branch-deploy]
  command = "npm i vite @vitejs/plugin-react-swc -D && node --experimental-modules netlify/functions/updatePackageJson.js && npm ci --legacy-peer-deps && npx vite build --config vite.config.ts"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# ... keep existing code (Enable bundler section)
