
# Netlify configuration for deployment
[build]
  command = "npm install --force && NODE_ENV=production npm run build"
  publish = "dist"
  functions = "netlify/functions"
  
# Specify Node.js version
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_ENV = "production"
  
# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Cache for fonts
[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache for images (can be revalidated)
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Performance optimization headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    # Enable compression
    Content-Encoding = "br"
    # Preload key assets
    Link = "</assets/js/vendor-react-*.js>; rel=preload; as=script, </assets/js/vendor-ui-*.js>; rel=preload; as=script"
    
# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "16"
  NPM_VERSION = "8"

# Add specific settings for preview deployments
[context.deploy-preview]
  command = "npm install --force && NODE_ENV=production npm run build"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "16"
  NPM_VERSION = "8"

# Branch deploy settings
[context.branch-deploy]
  command = "npm install --force && NODE_ENV=production npm run build"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "16"
  NPM_VERSION = "8"

# Enable bundler
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true
[build.processing.html]
  pretty_urls = true

# Set up deploy notifications
[build.notify]
  success = "Deploy successful! Site is live."
  error = "Deploy failed. Check build logs."
