
# Netlify configuration for deployment
[build]
  command = "npm install vite@6.2.1 @vitejs/plugin-react-swc@latest && npm ci --legacy-peer-deps && npx vite build"
  publish = "dist"
  functions = "netlify/functions"
  
# Specify Node.js version
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_APP_ENV = "production"
  VITE_VERSION = "6.2.1"
  NODE_ENV = "production"
  # Disable unnecessary language installations
  SKIP_GO_INSTALL = "true"
  SKIP_PYTHON_INSTALL = "true"
  SKIP_RUBY_INSTALL = "true"
  SKIP_RUST_INSTALL = "true"
  # Enable verbose logging for npm
  NPM_FLAGS = "--verbose --legacy-peer-deps"
  CACHE_DEPS = "true"
  
# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Cache for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Cache for fonts and images
[[headers]]
  for = "*.{woff,woff2,ttf,otf,png,jpg,jpeg,gif,webp,svg}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Performance optimization headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    
# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_VERSION = "6.2.1"
  SKIP_GO_INSTALL = "true"
  SKIP_PYTHON_INSTALL = "true"
  SKIP_RUBY_INSTALL = "true"
  SKIP_RUST_INSTALL = "true"
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Add specific settings for preview deployments
[context.deploy-preview]
  command = "npm install vite@6.2.1 @vitejs/plugin-react-swc@latest && npm ci --legacy-peer-deps && npx vite build"
  
[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_VERSION = "6.2.1"
  SKIP_GO_INSTALL = "true"
  SKIP_PYTHON_INSTALL = "true"
  SKIP_RUBY_INSTALL = "true"
  SKIP_RUST_INSTALL = "true"
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Branch deploy settings
[context.branch-deploy]
  command = "npm install vite@6.2.1 @vitejs/plugin-react-swc@latest && npm ci --legacy-peer-deps && npx vite build"

[context.branch-deploy.environment]
  NODE_ENV = "production"
  VITE_BASE_URL = "/"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_VERSION = "6.2.1"
  SKIP_GO_INSTALL = "true"
  SKIP_PYTHON_INSTALL = "true"
  SKIP_RUBY_INSTALL = "true"
  SKIP_RUST_INSTALL = "true"
  NPM_FLAGS = "--verbose --legacy-peer-deps"

# Dev settings
[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080
  framework = "#custom"
  publish = "dist"
  autoLaunch = false
  
# Post-processing settings
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Use Netlify's built-in caching for Vite projects
[[plugins]]
  package = "netlify-plugin-cache"  
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      "node_modules/.vite",
      ".netlify/functions-serve",
      ".netlify/cache/.vite",
      "dist"
    ]

# Configure the feed fetching plugin properly
[[plugins]]
  package = "netlify-plugin-fetch-feeds"
  [plugins.inputs]
    dataDir = "src/data/feeds"
    feeds = [
      { name = "css-tricks", url = "https://css-tricks.com/feed/", format = "rss" },
      { name = "netlify", url = "https://netlify.com/blog/index.xml", format = "rss" }
    ]
